version: '3.8'
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    command: uv run main.py
    container_name: yinxiai-bot
    depends_on:
      - lrcapi
    environment:
      - LRCAPI_URL=http://lrcapi:28883
    volumes:
      - .:/app
    restart: unless-stopped
  mongodb:
    image: mongo:8.0.12
    container_name: yinxiai-mongodb
    restart: unless-stopped
    ports:
      - "27021:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - yinxiai-mongodb:/data/db
    deploy:
      resources:
        limits:
          memory: 1G
  mongo-backup:
    image: alpine
    container_name: yinxiai-mongodb-backup
    restart: unless-stopped
    volumes:
      - ./data/mongodb/backup.sh:/backup.sh
      - ./data/mongodb:/backup
    depends_on:
      - mongodb
    entrypoint: ["/bin/sh", "-c", "apk add --no-cache mongodb-tools && echo '0 3 * * * /backup.sh' | crontab - && crond -f"]
    environment:
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
  lrcapi:
    image: hisatri/lrcapi:latest
    container_name: yinxiai-lrcapi
    expose:
      - "28883"
  ollama:
    image: ollama/ollama:latest
    container_name: yinxiai-ollama
    restart: unless-stopped
    ports:
      - "11434:11434"   # Ollama 預設 API 埠口
    volumes:
      - yinxiai-ollama_data:/root/.ollama  # 儲存模型與設定
    environment:
      - OLLAMA_ORIGINS=*
      - OLLAMA_KEEP_ALIVE=60
    deploy:
      resources:
        limits:
          memory: 2G
  redis:
    image: redis:latest
    container_name: yinxiai-redis
    restart: unless-stopped
    ports:
      - "6380:6379"
    volumes:
      - yinxiai-redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]
    deploy:
      resources:
        limits:
          memory: 1G
  qdrant:  
    image: qdrant/qdrant:latest  
    container_name: yinxiai-qdrant  
    restart: unless-stopped  
    ports:  
      - "6333:6333"  
      - "6334:6334"  
    volumes:  
      - ./data/qdrant/storage:/qdrant/storage  
      - ./data/qdrant/snapshots:/qdrant/snapshots
    
volumes:
  yinxiai-mongodb:
  yinxiai-redis_data:
  yinxiai-ollama_data: