version: '3.8'
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    command: uv run newbot2.py
    container_name: yinxi-dc-bot
    depends_on:
      - lrcapi
    environment:
      - LRCAPI_URL=http://lrcapi:28883
    volumes:
      - ./cmds/data.json:/app/cmds/data.json
      - ./data:/app/data
      - ./logs/bot.log:/app/logs/bot.log
      - ./setting.json:/app/setting.json
    restart: unless-stopped
  api_server:
    build: 
      context: .
      dockerfile: Dockerfile
    command: uv run api_server/server.py
    container_name: yinxi-dc-api-server
    ports:
      - "3000:3000"
    restart: unless-stopped
  mongodb:
    image: mongo:8.0.12
    container_name: yinxi-dc-mongodb
    restart: unless-stopped
    ports:
      - "27020:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - mongodb:/data/db
    deploy:
      resources:
        limits:
          memory: 1G
  mongo-backup:
    image: alpine
    container_name: yinxi-dc-mongodb-backup
    restart: unless-stopped
    volumes:
      - ./backup.sh:/backup.sh
      - ./data/mongodb:/backup
    depends_on:
      - mongodb
    entrypoint: ["/bin/sh", "-c", "apk add --no-cache mongodb-tools && echo '0 3 * * * /backup.sh' | crontab - && crond -f"]
    environment:
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
  lrcapi:
    image: hisatri/lrcapi:latest
    container_name: yinxi-dc-lrcapi
    expose:
      - "28883"
    
volumes:
  mongodb:
    driver: local